### ISSUE TITLE
Build error on Node 22.22.0

### ISSUE THREAD

**Issue by christhegrand** [mmdevries/eiows#30]
I can't get this library to create the eiows_v22.22.0 file on Node 22.22.0. These are the contents of my build_log file:

```
chris@Chriss-MacBook-Pro-7 eiows % cat build_log.txt 
gyp info it worked if it ends with ok
gyp info using node-gyp@11.2.0
gyp info using node@22.22.0 | darwin | arm64
gyp info find Python using Python version 3.12.8 found at "/usr/local/bin/python3"

gyp http GET https://nodejs.org/download/release/v22.22.0/node-v22.22.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v22.22.0/node-v22.22.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v22.22.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v22.22.0/SHASUMS256.txt
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args '/Users/chris/.nvm/versions/node/v22.22.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/Users/chris/Notability/Backend/node_modules/eiows/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/chris/.nvm/versions/node/v22.22.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/Users/chris/Library/Caches/node-gyp/22.22.0',
gyp info spawn args '-Dnode_gyp_dir=/Users/chris/.nvm/versions/node/v22.22.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/Users/chris/Library/Caches/node-gyp/22.22.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/Users/chris/Notability/Backend/node_modules/eiows',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/eiows/nodejs/src/addon.o
In file included from ../nodejs/src/addon.cpp:2:
In file included from ../nodejs/src/addon.h:9:
In file included from ../nodejs/src/node/src/crypto/crypto_tls.h:27:
In file included from ../nodejs/src/node/src/crypto/crypto_context.h:7:
In file included from ../nodejs/src/node/src/crypto/crypto_keys.h:6:
In file included from ../nodejs/src/node/src/crypto/crypto_util.h:15:
../nodejs/src/node/deps/ncrypto/ncrypto.h:208:46: warning: 'HMAC_CTX_free' is deprecated [-Wdeprecated-declarations]
  208 | using HMACCtxPointer = DeleteFnPtr<HMAC_CTX, HMAC_CTX_free>;
      |                                              ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/hmac.h:35:1: note: 'HMAC_CTX_free' has been explicitly marked deprecated here
   35 | OSSL_DEPRECATEDIN_3_0 void HMAC_CTX_free(HMAC_CTX *ctx);
      | ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:217:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
  217 | #   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
      |                                                 ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
   62 | #     define OSSL_DEPRECATED(since) __attribute__((deprecated))
      |                                                    ^
In file included from ../nodejs/src/addon.cpp:2:
In file included from ../nodejs/src/addon.h:9:
In file included from ../nodejs/src/node/src/crypto/crypto_tls.h:27:
In file included from ../nodejs/src/node/src/crypto/crypto_context.h:7:
In file included from ../nodejs/src/node/src/crypto/crypto_keys.h:6:
In file included from ../nodejs/src/node/src/crypto/crypto_util.h:15:
../nodejs/src/node/deps/ncrypto/ncrypto.h:202:49: warning: 'HMAC_CTX_free' is deprecated [-Wdeprecated-declarations]
  202 | using DeleteFnPtr = typename FunctionDeleter<T, function>::Pointer;
      |                                                 ^
../nodejs/src/node/deps/ncrypto/ncrypto.h:208:24: note: in instantiation of template type alias 'DeleteFnPtr' requested here
  208 | using HMACCtxPointer = DeleteFnPtr<HMAC_CTX, HMAC_CTX_free>;
      |                        ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/hmac.h:35:1: note: 'HMAC_CTX_free' has been explicitly marked deprecated here
   35 | OSSL_DEPRECATEDIN_3_0 void HMAC_CTX_free(HMAC_CTX *ctx);
      | ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:217:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
  217 | #   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
      |                                                 ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
   62 | #     define OSSL_DEPRECATED(since) __attribute__((deprecated))
      |                                                    ^
In file included from ../nodejs/src/addon.cpp:2:
In file included from ../nodejs/src/addon.h:9:
In file included from ../nodejs/src/node/src/crypto/crypto_tls.h:27:
In file included from ../nodejs/src/node/src/crypto/crypto_context.h:7:
In file included from ../nodejs/src/node/src/crypto/crypto_keys.h:6:
In file included from ../nodejs/src/node/src/crypto/crypto_util.h:15:
../nodejs/src/node/deps/ncrypto/ncrypto.h:211:37: warning: 'RSA_free' is deprecated [-Wdeprecated-declarations]
  211 | using RSAPointer = DeleteFnPtr<RSA, RSA_free>;
      |                                     ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/rsa.h:304:1: note: 'RSA_free' has been explicitly marked deprecated here
  304 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      | ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:217:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
  217 | #   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
      |                                                 ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
   62 | #     define OSSL_DEPRECATED(since) __attribute__((deprecated))
      |                                                    ^
In file included from ../nodejs/src/addon.cpp:2:
In file included from ../nodejs/src/addon.h:9:
In file included from ../nodejs/src/node/src/crypto/crypto_tls.h:27:
In file included from ../nodejs/src/node/src/crypto/crypto_context.h:7:
In file included from ../nodejs/src/node/src/crypto/crypto_keys.h:6:
In file included from ../nodejs/src/node/src/crypto/crypto_util.h:15:
../nodejs/src/node/deps/ncrypto/ncrypto.h:202:49: warning: 'RSA_free' is deprecated [-Wdeprecated-declarations]
  202 | using DeleteFnPtr = typename FunctionDeleter<T, function>::Pointer;
      |                                                 ^
../nodejs/src/node/deps/ncrypto/ncrypto.h:211:20: note: in instantiation of template type alias 'DeleteFnPtr' requested here
  211 | using RSAPointer = DeleteFnPtr<RSA, RSA_free>;
      |                    ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/rsa.h:304:1: note: 'RSA_free' has been explicitly marked deprecated here
  304 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      | ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:217:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
  217 | #   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
      |                                                 ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
   62 | #     define OSSL_DEPRECATED(since) __attribute__((deprecated))
      |                                                    ^
In file included from ../nodejs/src/addon.cpp:2:
In file included from ../nodejs/src/addon.h:9:
In file included from ../nodejs/src/node/src/crypto/crypto_tls.h:27:
In file included from ../nodejs/src/node/src/crypto/crypto_context.h:7:
In file included from ../nodejs/src/node/src/crypto/crypto_keys.h:6:
In file included from ../nodejs/src/node/src/crypto/crypto_util.h:15:
../nodejs/src/node/deps/ncrypto/ncrypto.h:658:19: warning: 'DH_free' is deprecated [-Wdeprecated-declarations]
  658 |   DeleteFnPtr<DH, DH_free> dh_;
      |                   ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/dh.h:211:1: note: 'DH_free' has been explicitly marked deprecated here
  211 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      | ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:217:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
  217 | #   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
      |                                                 ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
   62 | #     define OSSL_DEPRECATED(since) __attribute__((deprecated))
      |                                                    ^
In file included from ../nodejs/src/addon.cpp:2:
In file included from ../nodejs/src/addon.h:9:
In file included from ../nodejs/src/node/src/crypto/crypto_tls.h:27:
In file included from ../nodejs/src/node/src/crypto/crypto_context.h:7:
In file included from ../nodejs/src/node/src/crypto/crypto_keys.h:6:
In file included from ../nodejs/src/node/src/crypto/crypto_util.h:15:
../nodejs/src/node/deps/ncrypto/ncrypto.h:202:49: warning: 'DH_free' is deprecated [-Wdeprecated-declarations]
  202 | using DeleteFnPtr = typename FunctionDeleter<T, function>::Pointer;
      |                                                 ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/dh.h:211:1: note: 'DH_free' has been explicitly marked deprecated here
  211 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      | ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:217:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
  217 | #   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
      |                                                 ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
   62 | #     define OSSL_DEPRECATED(since) __attribute__((deprecated))
      |                                                    ^
In file included from ../nodejs/src/addon.cpp:2:
In file included from ../nodejs/src/addon.h:9:
In file included from ../nodejs/src/node/src/crypto/crypto_tls.h:27:
In file included from ../nodejs/src/node/src/crypto/crypto_context.h:7:
In file included from ../nodejs/src/node/src/crypto/crypto_keys.h:6:
In file included from ../nodejs/src/node/src/crypto/crypto_util.h:15:
../nodejs/src/node/deps/ncrypto/ncrypto.h:948:23: warning: 'EC_KEY_free' is deprecated [-Wdeprecated-declarations]
  948 |   DeleteFnPtr<EC_KEY, EC_KEY_free> key_;
      |                       ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/ec.h:1022:1: note: 'EC_KEY_free' has been explicitly marked deprecated here
 1022 | OSSL_DEPRECATEDIN_3_0 void EC_KEY_free(EC_KEY *key);
      | ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:217:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
  217 | #   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
      |                                                 ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
   62 | #     define OSSL_DEPRECATED(since) __attribute__((deprecated))
      |                                                    ^
In file included from ../nodejs/src/addon.cpp:2:
In file included from ../nodejs/src/addon.h:9:
In file included from ../nodejs/src/node/src/crypto/crypto_tls.h:27:
In file included from ../nodejs/src/node/src/crypto/crypto_context.h:7:
In file included from ../nodejs/src/node/src/crypto/crypto_keys.h:6:
In file included from ../nodejs/src/node/src/crypto/crypto_util.h:15:
../nodejs/src/node/deps/ncrypto/ncrypto.h:202:49: warning: 'EC_KEY_free' is deprecated [-Wdeprecated-declarations]
  202 | using DeleteFnPtr = typename FunctionDeleter<T, function>::Pointer;
      |                                                 ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/ec.h:1022:1: note: 'EC_KEY_free' has been explicitly marked deprecated here
 1022 | OSSL_DEPRECATEDIN_3_0 void EC_KEY_free(EC_KEY *key);
      | ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:217:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
  217 | #   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
      |                                                 ^
/Users/chris/Library/Caches/node-gyp/22.22.0/include/node/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
   62 | #     define OSSL_DEPRECATED(since) __attribute__((deprecated))
      |                                                    ^
In file included from ../nodejs/src/addon.cpp:2:
In file included from ../nodejs/src/addon.h:9:
../nodejs/src/node/src/crypto/crypto_tls.h:70:9: error: unknown type name 'SSLPointer'; did you mean 'ncrypto::SSLPointer'?
   70 |   const SSLPointer *getSSL() const { return &ssl_; }
      |         ^~~~~~~~~~
      |         ncrypto::SSLPointer
../nodejs/src/node/deps/ncrypto/ncrypto.h:702:7: note: 'ncrypto::SSLPointer' declared here
  702 | class SSLPointer final {
      |       ^
In file included from ../nodejs/src/addon.cpp:2:
../nodejs/src/addon.h:41:9: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
   41 |         Local<Function>::New(isolate, noop)->Call(isolate->GetCurrentContext(), Null(isolate), 0, nullptr);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../nodejs/src/addon.h:151:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
  151 |     array->Set(isolate->GetCurrentContext(), 0, Integer::New(isolate, address.port));
      |     ^~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../nodejs/src/addon.h:152:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
  152 |     array->Set(isolate->GetCurrentContext(), 1, String::NewFromUtf8(isolate, address.address, NewStringType::kNormal).ToLocalChecked());
      |     ^~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../nodejs/src/addon.h:153:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
  153 |     array->Set(isolate->GetCurrentContext(), 2, String::NewFromUtf8(isolate, address.family,  NewStringType::kNormal).ToLocalChecked());
      |     ^~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../nodejs/src/addon.h:177:9: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
  177 |         Local<Function>::New(sc->isolate, sc->jsCallback)->Call(sc->isolate->GetCurrentContext(), Null(sc->isolate), 0, nullptr);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../nodejs/src/addon.h:263:9: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
  263 |         Local<Function>::New(isolate, *connectionCallback)->Call(isolate->GetCurrentContext(), Null(isolate), 1, argv);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../nodejs/src/addon.h:280:13: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
  280 |             Local<Function>::New(isolate, *messageCallback)->Call(isolate->GetCurrentContext(), Null(isolate), 2, argv);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../nodejs/src/addon.h:275:49: warning: lambda capture 'group' is not used [-Wunused-lambda-capture]
  275 |     group->onMessage([isolate, messageCallback, group](eioWS::WebSocket *webSocket, const char *message, size_t length, eioWS::OpCode opCode) {
      |                                               ~~^~~~~
../nodejs/src/addon.h:300:9: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
  300 |         Local<Function>::New(isolate, *disconnectionCallback)->Call(isolate->GetCurrentContext(), Null(isolate), 4, argv);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../nodejs/src/addon.h:347:9: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
  347 |         object->Set(isolate->GetCurrentContext(), String::NewFromUtf8(isolate, "group", NewStringType::kNormal).ToLocalChecked(), group);
      |         ^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../nodejs/src/addon.cpp:7:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    7 |     exports->Set(isolate->GetCurrentContext(), String::NewFromUtf8(isolate, "server", NewStringType::kNormal).ToLocalChecked(), Namespace(isolate).object);
      |     ^~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19 warnings and 1 error generated.
make: *** [Release/obj.target/eiows/nodejs/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/Users/chris/.nvm/versions/node/v22.22.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:219:23)
gyp ERR! System Darwin 24.4.0
gyp ERR! command "/Users/chris/.nvm/versions/node/v22.22.0/bin/node" "/Users/chris/.nvm/versions/node/v22.22.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/chris/Notability/Backend/node_modules/eiows
gyp ERR! node -v v22.22.0
gyp ERR! node-gyp -v v11.2.0
gyp ERR! not ok 
```

Am I missing a dependency? This is the error:

```
In file included from ../nodejs/src/addon.cpp:2:
In file included from ../nodejs/src/addon.h:9:
../nodejs/src/node/src/crypto/crypto_tls.h:70:9: error: unknown type name 'SSLPointer'; did you mean 'ncrypto::SSLPointer'?
   70 |   const SSLPointer *getSSL() const { return &ssl_; }
      |         ^~~~~~~~~~
      |         ncrypto::SSLPointer
```

I am on version 7.1.2 of the library and MacOS 15.4.

**Comment by mmdevries** [comment]
Can you try the 8.2.0 eiows version?

**Comment by christhegrand** [comment]
Thanks, it works on 8.2.0. I'll close this.
